name: portfolio
description: Timilehin Jegede's Portfolio
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # launching urls
  url_launcher: ^6.0.20

  # declarative routing 
  go_router: ^3.0.7

  # state management
  flutter_riverpod: ^1.0.3

  # network requests
  dio: ^4.0.6

  # responsive layout
  responsive_builder: ^0.4.2

  # responsive text widgets
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter
  
  # linting and static analysis
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/pngs/
    - assets/images/pngs/logos/
    - assets/images/svgs/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic